### ISSUE TITLE
xcode 8 用pod 继承jspatchplatform 的时候编译出错

### ISSUE THREAD

**Issue by qylibohao** [bang590/JSPatchPlatform#3]
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_JSPatch", referenced from:
 objc-class-ref in JSPatchManager.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by ghost** [comment]
@bang590 
生成警告的时候会有这么一个note 
`note: Linking a static library that was built with -gmodules, but the module cache was not found.  Redistributable static libraries should never be built with module debugging enabled.  The debug experience will be degraded due to incomplete debug information.`

我自己的一些库也会报这个警告,解决方法是`Enable Clang Module Debuging ->NO`

有空的时候请更新一发,不然工程里一堆警告看着不太舒服

**Comment by bang590** [comment]
@FinderTiwk 收到
